---
# common variables for all

ansible_connection: local
ansible_become: yes
ansible_become_method: sudo
k3s_version: v1.22.3+k3s1
ansible_user: ansible
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""